// <auto-generated />
using System;
using APIColas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIColas.Migrations
{
    [DbContext(typeof(ColasDbContext))]
    partial class ColasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIColas.Models.DiaSimulado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Descargas")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("LlegadasNocturnas")
                        .HasColumnType("int");

                    b.Property<double>("NumeroAleatorioDescargas")
                        .HasColumnType("float");

                    b.Property<double>("NumeroAleatorioLlegadas")
                        .HasColumnType("float");

                    b.Property<int>("RetrasosDiaAnterior")
                        .HasColumnType("int");

                    b.Property<int>("SimulacionId")
                        .HasColumnType("int");

                    b.Property<int>("TotalADescargar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionId");

                    b.ToTable("ResultadosSimulacion");
                });

            modelBuilder.Entity("APIColas.Models.PromediosSimulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("PromedioDescargasDiarias")
                        .HasColumnType("float");

                    b.Property<double>("PromedioLlegadasNocturnas")
                        .HasColumnType("float");

                    b.Property<double>("PromedioRetrasos")
                        .HasColumnType("float");

                    b.Property<int>("SimulacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionId")
                        .IsUnique();

                    b.ToTable("PromediosSimulacion");
                });

            modelBuilder.Entity("APIColas.Models.Simulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("APIColas.Models.DiaSimulado", b =>
                {
                    b.HasOne("APIColas.Models.Simulacion", "Simulacion")
                        .WithMany("Dias")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("APIColas.Models.PromediosSimulacion", b =>
                {
                    b.HasOne("APIColas.Models.Simulacion", "Simulacion")
                        .WithOne("Promedios")
                        .HasForeignKey("APIColas.Models.PromediosSimulacion", "SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("APIColas.Models.Simulacion", b =>
                {
                    b.Navigation("Dias");

                    b.Navigation("Promedios")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
